export enum ButtonTestId {
  PLUS_BTN = 'PLUS_BTN',
  MINUS_BTN = 'MINUS_BTN',
  REPLY_BTN = 'REPLY_BTN',
  EDIT_COMMENT_BTN = 'EDIT_COMMENT_BTN',
  DELETE_COMMENT_BTN = 'DELETE_COMMENT_BTN',
  SEND_COMMENT_BTN = 'SEND_COMMENT_BTN',
  UPDATE_COMMENT_BTN = 'UPDATE_COMMENT_BTN',
}

export default ButtonTestId;
